#!/bin/bash

set -euo pipefail

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


cd "${BASE_DIR}"

IMAGE="nginx"
IMAGE_TAG="1.11.3"
IMAGE_NAME="everydayhero/${IMAGE}"
BUILD_NAME="${IMAGE}-build"

docker rmi -f "${BUILD_NAME}" || true

echo "+++ Build :nginx:"
docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .

echo "+++ Push to registry"
docker push "${IMAGE_NAME}:${IMAGE_TAG}"

echo "+++ Cleanup"
docker rmi -f "${BUILD_NAME}" || true
